#!/bin/bash
echo "      W E L C O M E   "
echo "             T O    "
echo "                 T H E     "
echo "                     S H O W     "
echo "        \`        \*         \*         \`      "
echo "  / __       __       __       __     __ \  "
echo "                                            "
echo "      (●ˇ∀ˇ●)      (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧            "
echo "      ~~~~~~~      --------                 "
echo "          (✪ ω ✪)              (;´༎ຶД༎ຶ`)     "
echo "____________________________________________"
echo " | |    o        `     --        .       | |"
echo " | | '      @        ()             *    | |"
echo " | |     !        ~              ~       | |"
